version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: portfolio_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio-network

  backend:
    build:
      context: ../portfolio-backend
      dockerfile: Dockerfile
    container_name: portfolio_backend
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}       # <-- اصلاح شد
      - DB_PASSWORD=${DB_PASSWORD} # <-- اصلاح شد
      - DB_NAME=${DB_NAME}       # <-- اصلاح شد
    networks:
      - portfolio-network

  frontend:
    build:
      context: ../raheemtermeh/terme-linooxel/terme-linooxel-ba829071cab2540bb0693471e570a4efaf37b054
      dockerfile: Dockerfile
    container_name: portfolio_frontend
    restart: always
    networks:
      - portfolio-network

  nginx:
    image: nginx:1.21-alpine
    container_name: portfolio_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - portfolio-network

volumes:
  postgres_data:

networks:
  portfolio-network:
    driver: bridge